// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myApi.Migrations;

#nullable disable

namespace myApi.Migrations
{
    [DbContext(typeof(TweetDbContext))]
    [Migration("20240815015328_UpdateUserEntity")]
    partial class UpdateUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("myApi.Models.Tweet", b =>
                {
                    b.Property<int>("TweetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TweetMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TweetId");

                    b.ToTable("Tweet");

                    b.HasData(
                        new
                        {
                            TweetId = 1,
                            CreatedAt = new DateTime(2024, 8, 14, 21, 53, 27, 368, DateTimeKind.Local).AddTicks(1591),
                            TweetMessage = "Hello there! This is my first tweet!👋",
                            UserName = "TestUser1"
                        },
                        new
                        {
                            TweetId = 2,
                            CreatedAt = new DateTime(2024, 8, 14, 21, 53, 27, 368, DateTimeKind.Local).AddTicks(1594),
                            TweetMessage = "Ahh! I love this app, so cool!👏",
                            UserName = "TestUser2"
                        });
                });

            modelBuilder.Entity("myApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
